language: node_js
node_js:
  - "12"

deploy_service: &DEPLOY_SERVICE
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  stages:
    - name: script
      if: branch = master

  install:
    - npm install -g serverless
    - travis_retry npm install -s
    - cd ${SERVICE_PATH}
    - travis_retry npm install -s
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s prod
    - cd -

jobs:
  include:
    - stage: deploy
    - <<: *DEPLOY_SERVICE
      name: "Deploy Graphql Server"
      env:
        - SERVICE_PATH="graphql"
    - <<: *DEPLOY_SERVICE
      name: "Deploy React Frontend"
      env:
        - SERVICE_PATH="frontend"
