language: node_js
node_js:
  - '12'

deploy_service: &DEPLOY_SERVICE
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  install:
    - npm install -g serverless
    - travis_retry npm install -s
    - cd ${SERVICE_PATH}
    - travis_retry npm install -s
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s ${TRAVIS_BRANCH}
    - cd -
    on:
      branch: master

jobs:
  include:
    - <<: *DEPLOY_SERVICE
      name: 'Deploy Graphql Server'
      env:
        - SERVICE_PATH="graphql"
