service: apollo-lambda
provider:
    name: aws
    runtime: nodejs12.x
    region: us-west-2
    lambdaHashingVersion: 20201221
    environment:
        RecipeDB: ${self:custom.RecipeDB}

    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:DescribeTable
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                      - dynamodb:GetRecords
                      - dynamodb:GetShardIterator
                      - dynamodb:DescribeStream
                      - dynamodb:ListStream
                  Resource:
                      - 'Fn::GetAtt': [RecipeDB, Arn]
functions:
    graphql:
        handler: src/server.graphql_handler
        events:
            - http:
                  path: graphql
                  method: post
                  cors: true
            - http:
                  path: graphql
                  method: get
                  cors: true
plugins:
    - serverless-dotenv-plugin
    - serverless-offline
    - serverless-webpack

custom:
    webpack:
        includeModules: true
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}
    RecipeDB: ${self:custom.stage}-recipes
    tableThroughputs:
        prod: 1
        default: 1
    tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

resources:
    - ${file(resources/recipe-db.yml)}
