service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  lambdaHashingVersion: 20201221
functions:
  graphql:
    handler: src/server.graphql_handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack
custom:
  webpack:
    includeModules: true
