Resources:
    RecipeDB:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.RecipeDB}
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S

            KeySchema:
                - AttributeName: id
                  KeyType: HASH

            # Set the capacity based on the stage
            ProvisionedThroughput:
                ReadCapacityUnits: ${self:custom.tableThroughput}
                WriteCapacityUnits: ${self:custom.tableThroughput}
