Resources:
    UserDB:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.UserDB}
            AttributeDefinitions:
                - AttributeName: email
                  AttributeType: S

            KeySchema:
                - AttributeName: email
                  KeyType: HASH

            # Set the capacity based on the stage
            ProvisionedThroughput:
                ReadCapacityUnits: ${self:custom.tableThroughput}
                WriteCapacityUnits: ${self:custom.tableThroughput}
